# Generated by Django 6.0.2 on 2026-02-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Готово')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
